name: app-build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: subosito/flutter-action@v2
        with-version: '3.3.9'
        channel: 'stable'
      - run: flutter --version
      - run: echo $FIREBASE_SECRETS_CONTENT | base64 --decode > lib/firebase/secrets.dart
        env:
          FIREBASE_SECRETS_CONTENT: ${{ secrets.FIREBASE_SECRETS_CONTENT }}