#!/bin/sh

if [ "$(git rev-parse --is-shallow-repository)" = "true" ]; then
  git fetch --quiet --unshallow
fi

git tag | grep "^v[0-9]\+\.[0-9]\+\.[0-9]\+$" | xargs -I {} sh -c 'git merge-base --is-ancestor $1 origin/main && echo $1' - {} | sort -t "." -k1,1n -k2,2n -k3,3n | tail -1 | sed 's/v\([0-9]\{1,\}\.[0-9]\{1,\}\.[0-9]\{1,\}\).*/\1/'
