name: flutter-checks
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with-version: '3.3.9'
        channel: 'stable'
      - run: flutter --version
      - run: flutter pub get
      - run: flutter analyze

  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.9'
          channel: 'stable'
      - run: flutter pub get
      - run: flutter test --coverage .
      - uses: codecov/codecov-action@v3