name: flutter-checks
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/app-build
        secrets:
          FIREBASE_SECRETS_CONTENT: ${{ secrets.FIREBASE_SECRETS_CONTENT }}
      - run: flutter analyze

  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/app-build
        secrets:
          FIREBASE_SECRETS_CONTENT: ${{ secrets.FIREBASE_SECRETS_CONTENT }}
      - run: flutter test --coverage .
      - uses: codecov/codecov-action@v3