name: pdd
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  pdd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: g4s8/pdd-action@master
