name: pull-request
on:
  pull_request:
    branches:
      - main

env:
  GITHUB_PR_NUMBER: ${{ github.event.pull_request.number }}
  GITHUB_PR_TITLE: ${{ github.event.pull_request.title }}  

jobs:
  changelog:
    if: ${{ startsWith(env.GITHUB_PR_TITLE, 'Upgrade version to') != true }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ./scripts/verify-changelog pending/changes/$GITHUB_PR_NUMBER.md

